name: Test code and deploy

on:
  push:
    branches: [master]

jobs:
  test:
    name: Test code
    runs-on: ubuntu-latest
    
    steps:
      - name: Get code from repo
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
    
      - name: Install dependencies
        run: pip install colorama
      
      - name: Build
        run: python проверка.py build
      
      - name: Run tests
        run: python -m unittest -k "test_*.py" 
